### ISSUE TITLE
Preserve shorthand HEX value or setting to always convert to shorthand if possible

### ISSUE THREAD

**Issue by alexilyaev** [rmaksim/Sublime-Text-2-Inc-Dec-Value#32]
Similar to how ColorConvert handles it:
https://github.com/TheDutchCoder/ColorConvert

Converting  ```#fff``` results back to ```#ffffff; /* alpha: 1 */```

At least I'd expect to preserve the initial value, but better yet, a setting to always convert to shorthand would be nice (in ColorConvert it's default behavior).

**Comment by rmaksim** [comment]
fixed in https://github.com/rmaksim/Sublime-Text-2-Inc-Dec-Value/commit/c2f80b04b3d4817721e24c0078d3495f0f5216e3
