### ISSUE TITLE
Setting or key to convert to RGB vs RGBA

### ISSUE THREAD

**Issue by alexilyaev** [rmaksim/Sublime-Text-2-Inc-Dec-Value#33]
Is it possible to convert to RGB vs RGBA?

RGBA is supported only from IE9:
http://msdn.microsoft.com/en-us/library/hh781508(v=vs.85).aspx (search rgba)
http://caniuse.com/#search=rgba

If added, should probably remove the ```alpha``` comment after conversion.

**Comment by rmaksim** [comment]
This issue is still relevant?

**Comment by rmaksim** [comment]
fixed in https://github.com/rmaksim/Sublime-Text-2-Inc-Dec-Value/commit/acfc441cf80170777a6794cc65cbb60a683ce4e7
