### ISSUE TITLE
Setting for spacing in RGB values

### ISSUE THREAD

**Issue by alexilyaev** [rmaksim/Sublime-Text-2-Inc-Dec-Value#34]
Following [Idiomatic CSS](https://github.com/necolas/idiomatic-css#4-format)

Would be nice to have a setting to define the spacing between the values of the RGB
```
rgba(0,0,0,1);
```
vs
```
rgba(0, 0, 0, 1);
```

**Comment by rmaksim** [comment]
fixed in https://github.com/rmaksim/Sublime-Text-2-Inc-Dec-Value/commit/5b0bca23e46d832c5ce84eb24f726a7f1bc8897b
