### ISSUE TITLE
Enums css properties with dashes (-)

### ISSUE THREAD

**Issue by evanre** [rmaksim/Sublime-Text-2-Inc-Dec-Value#40]
Hi, I try to customize list of enums. And I find a problem with enum items that contains few dashes. (f.e. `ease-in-out`, `nth-of-child` etc.). When i list this items and reach some property with few dashes it stops listing.

P.S. By the way, it would be cool to improve lists functionality, e.g. to expand list of available characters. To male possible write something like this:
```[":first-child", ":last-child", ":last-of-type", ":nth-child()", ":nth-last-child()", ":nth-of-type()"],```

P.P.S Sorry for my English, maybe, a I can explain my problem better in Russian? :)

**Comment by evanre** [comment]
One more thing. I Have a problem with properties that contains two and more words. e.g. You add by dafault list  `["margin", "padding"]` If i had combine property `margin: 10px 20px;` All warks good, but it doesn't with sides `-left, -right` .etc. It would be great to make possible change words separetly {`margin-padding-border`}-{`left-right-top-bottom`}:... Thanks for a great tool :)

**Comment by rmaksim** [comment]
fixed first part of issue - items that contains few dashes
see example in [settings](https://github.com/rmaksim/Sublime-Text-2-Inc-Dec-Value/blob/master/inc_dec_value.sublime-settings#L36)
