### ISSUE TITLE
Insert cutting preceding  characters 

### ISSUE THREAD

**Issue by LeonardoGentile** [rmaksim/Sublime-Text-2-Inc-Dec-Value#41]
Hello,
I've tested that when using any key combination for the `ins_min`, `ins_max` or `ins_all` actions something wrong happens.
That is when hitting the corresponding shortcuts the values are added but this delete the preceding chars in the current line. I cannot be sure but it seems that the chars deleted are 4, or maybe it's just a tabulation.

**Comment by rmaksim** [comment]
Hello,
Can you write an example

**Comment by LeonardoGentile** [comment]
In this example I've set my shortcuts as this
```
{ "keys": ["alt+enter"], "command": "inc_dec_value", "args": { "action": "ins_min" }},
```
Then I've created an example using a simple javascript literal, as you can see in the gif attached.
Everytime I hit the shortcut the number one is added but also some characters (in this case 1 char) disappear from the left. Sometimes it seems to be more than one chars, I cannot tell on when this actually happens.
![nk1ealuhb2](https://cloud.githubusercontent.com/assets/412061/16408029/0656f288-3d17-11e6-8b16-072a84a721fe.gif)

**Comment by rmaksim** [comment]
try default hotkey 
` { "keys": ["alt+down"],       "command": "inc_dec_value", "args": { "action": "dec_min" } },`
maybe on ["alt+enter"] something else

**Comment by LeonardoGentile** [comment]
@rmaksim `inc_min`, `dec_min` and all other actions not related to **ins** are working correctly. 
I have changed the shortcut of `ins_min` to  
```
{ "keys": ["alt+pageup"], "command": "inc_dec_value", "args": { "action": "ins_min" }}
```
but nothing changes, still some characters are deleted from the left

**Comment by rmaksim** [comment]
yeh, I've already forgotten...
https://github.com/rmaksim/Sublime-Text-2-Inc-Dec-Value/pull/37
> I added the ability to insert incrementing numbers at the selections

insert -> **at the selections**

Now you can do just that.

**Comment by rmaksim** [comment]
fixed, update and try to use
